[package]
name = "soa-rs-testing"
version = "0.9.0"
edition = "2024"
publish = false

[dependencies]
criterion = "0.5.1"
rand = "0.9.0"
serde = "1.0.199"
serde_json = "1.0.116"

[dependencies.soa-rs]
version = "0.9.1"
path = ".."
features = ["serde"]

[[bench]]
name = "benchmark"
harness = false
